### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by SadiaAfrinPurba** [MiuLab/PLM-ICD#3]
Thank you for the amazing work. I have two concerns: 

1. Can we use a custom dataset instead of MIMIC data?
2. Can you please share the trained model artifacts?

**Comment by chaoweihuang** [comment]
Hi,

I appreciate your interest in our work!
Regarding 1, sure you can use a custom dataset instead of MIMIC. You can convert your own dataset to the following csv format and then run the scripts:
```
SUBJECT_ID,HADM_ID,text,label,length
158,169433,admission date discharge date date of birth sex m service med blumga for content of this discharge summary please refer to the discharge summary dictated by myself with discharge date of for content dr first name stitle first name3 lf dictated by last name namepattern1 medquist36 d t job job number,532.40;493.20;V45.81;412;401.9;44.43,51
```
The example above shows the header of the CSV file and the first row of data.

Regarding 2, I've uploaded three trained models (for MIMIC-3 full, MIMIC-3 50, MIMIC2) to Google Drive: https://drive.google.com/drive/folders/1oJLgLKu_NZxsSTXU9uFVehxXXJYzTalO?usp=sharing

Best,
Chao-Wei
