### ISSUE TITLE
Error Loading Tokenizer for Pretrained Model

### ISSUE THREAD

**Issue by Ahmed-Mortadi** [MiuLab/PLM-ICD#8]
Hello Dr. Yun-Nung and the PLM-ICD team,

First of all, thank you for your great work on PLM-ICD.

I am trying to **reproduce your results**, and I have encountered an issue while running the following command:

**python3 run_icd.py \
    --train_file /content/MIMIC_3/train_full.csv \
    --validation_file /content/MIMIC_3/dev_full.csv \
    --max_length 3072 \
    --chunk_size 128 \
    --model_name_or_path /content/roberta-pm-m3-voc-da-laat-6144-128-bs8-e20-warmup \
    --per_device_eval_batch_size 1 \
    --num_train_epochs 0 \
    --output_dir . \
    --model_type roberta \
    --model_mode laat**

It seems like the model loaded successfully, and its configurations were printed, but I encountered the following error related to a **missing tokenizer**:

Traceback (most recent call last):
  File "/content/src/run_icd.py", line 488, in <module>
    main()
  File "/content/src/run_icd.py", line 267, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 745, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1838, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/content/roberta-pm-m3-voc-da-laat-6144-128-bs8-e20-warmup'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/content/roberta-pm-m3-voc-da-laat-6144-128-bs8-e20-warmup' is the correct path to a directory containing all relevant files for a RobertaTokenizerFast tokenizer.

I would greatly appreciate any assistance or guidance provided, thank you in advance.

**Comment by FareedKhan-dev** [comment]
hello @AHMAD-DOMA, i am also trying to replicate their work can you please tell me i have already downloaded their trained model, but how to use them for inferencing, can you please guide?

**Comment by FareedKhan-dev** [comment]
hello @AHMAD-DOMA did you figure it out? How did you solve this problem?

**Comment by Ahmed-Mortadi** [comment]
I apologize for the delayed response, @FareedKhan-dev. I've successfully resolved the issue by downloading the RoBERTa-base-PM-M3-Voc-hf model from the following source: https://dl.fbaipublicfiles.com/biolm/RoBERTa-base-PM-M3-Voc-hf.tar.gz. After downloading, I uncompressed the file and then adjusted the "model_name_or_path" parameter to point to the directory's path.

**Comment by FareedKhan-dev** [comment]
Thank you @AHMAD-DOMA  for your response and for sharing the steps you took to resolve the issue. I really appreciate your help.
My task is also focused on replicating the results from the paper, and I encountered the same problem. While I did eventually find a solution, it took a considerable amount of time. Your confirmation that you followed similar steps to resolve the issue is reassuring.
I noticed that you mentioned another issue regarding the results. I will certainly be sharing my results in that issue as well.

**Comment by chaoweihuang** [comment]
Hi @AHMAD-DOMA and @FareedKhan-dev,

Sorry for the (really) late reply.
Thank you for your interest in our work!
I believe this is caused by using newer versions of the transformers library, while this repo used an older version.
I'm glad that you have solved the issue!

I have uploaded the corresponding tokenizer files to the released checkpoints, so future users wouldn't need to download them manually.

Best,
Chao-Wei
